### ISSUE TITLE
core/notifications-for: path for web hook should be configurable 

### ISSUE THREAD

**Issue by abendt** [flosell/lambdacd-git#25]
we just switched to a setup where we run multiple pipelines within the same server (e.g. https://github.com/flosell/lambdacd-cookie-cutter-pipeline-example).

We also use Post-Commit Hooks instead of Polling. The provided function (core/notifications-for) does not allow to set the path, so registration of multiple endpoints is a bit clumsy (directly invoke notify-git-handler).

It would be nice if notifications-for would make the path parameter configurable.

EDIT: adding multiple endpoints (each for one pipeline) does not seem to work. The request is received, however no build is triggered.

**Comment by flosell** [comment]
Thanks for the feedback! I [extended](https://github.com/flosell/lambdacd-cookie-cutter-pipeline-example/blob/c9da3cf/src/pipeline_templates/pipeline.clj#L44) the example to use LambdaCD git and notifications and couldn't reproduce the issue. 

One thing to keep in mind is that (similar to Jenkins), the hooks do not trigger a build, they trigger a check for changes that may trigger a build so when no changes were found in the repository, no build is triggered. 
You should see a message (`Received notification. Polling out of schedule`) in the output of the waiting step when such a check is happening.

As for your suggestion of setting the path, I'm not totally against the idea, however I'd like to get a better feeling what you are struggling with. At least in my example, the change was minimal since `compojure/context` was already necessary to expose UI and APIs for multiple projects. 

Could you provide a sample of what you are trying to do?

**Comment by abendt** [comment]
thanks! the extended example was very helpful. i was not aware that I could add the hook within the pipeline specific context e.g. /app1/notify-git and /app2/notify-git. everything works fine now!
