### ISSUE TITLE
Identity file is not picked up outside of "identity repository"

### ISSUE THREAD

**Issue by magnars** [flosell/lambdacd-git#28]
Using the `:identity-file` flag does not work as advertised. It takes the full path, but has to be located in the folder returned by the jsch `getIdentityRepository` to be used.

**Comment by magnars** [comment]
My last statement turns out to not be entirely precise. Even moving the file to `~/.ssh/` does not make it part of the collection returned by `(.getIdentities (.getIdentityRepository jsch))` - so now I am at a total loss for how to use this feature. Any hints would be appreciated!

**Comment by flosell** [comment]
Thanks for the feedback! This option was introduced in #12 and for the use-case there (wanting to select which key to use when multiple keys are found) it probably works fine. 

But reading the docs I can see how you might expect a different behavior: That you can specify a keyfile that's being used no matter where it is or how SSH might pick it up. 

For now, I tried to clarify the README but I agree this setting should be extended so that any file can be set as an identity file. 

As a workaround, configuring the identity file in `~/.ssh/config` or using an SSH agent should work.

**Comment by magnars** [comment]
Thanks, that makes sense. I still don't know how to make `(.getIdentities (.getIdentityRepository jsch))` pick up my other identity file, but I guess that's a question for JSch!

**Comment by magnars** [comment]
Having digged into this for a while, I found this code: https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/transport/JschConfigSessionFactory.java#L379-L389

It seems only files called `identity`, `id_rsa` or `id_dsa` in the home directory will be part of the default identity repository. So the `:identity-file` setting can only choose between these three files.
